// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: page1_start

#include "../include/ui_h/ui.h"
#include "../include/ui_h/ui_helpers.h"


///////////////////// VARIABLES ////////////////////


// SCREEN: ui_page1_Screen1_start
void ui_page1_Screen1_start_screen_init(void);
lv_obj_t * ui_page1_Screen1_start;
lv_obj_t * ui_page1_Label1_loadingtext;
lv_obj_t * ui_pag1_Bar1_loading;
lv_obj_t * ui____initial_actions0;





//第二个显示页面
// SCREEN: ui_page2_Screen2_weather
void ui_page2_Screen2_weather_screen_init(void);
lv_obj_t * ui_page2_Screen2_weather;
lv_obj_t * ui_page2_Panel_main;
lv_obj_t * ui_page2_Label1_date;
lv_obj_t * ui_page2_Label1_week;
lv_obj_t * ui_page2_Label1_nongli;
lv_obj_t * ui_page2_Label1_time;
lv_obj_t * ui_page2_Panel2_main_ht;
lv_obj_t * ui_page2_Image1_wendu;
lv_obj_t * ui_page2_Image2_shidu;
lv_obj_t * ui_page2_Label1_temp;
lv_obj_t * ui_page2_Label1_wendu;
lv_obj_t * ui_page2_Label1_shidu;
lv_obj_t * ui_page2_Label1_suget;
lv_obj_t * ui_page2_Label1_locsl;
lv_obj_t * ui_page2_Image4_local;
lv_obj_t * ui_page2_Label1_gengxing;
lv_obj_t * ui____initial_actions0;



///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_page2_Screen2_weather_screen_init();
    ui_page1_Screen1_start_screen_init();
    
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_page2_Screen2_weather);
}
