// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: page2_weather

#ifndef _PAGE2_WEATHER_UI_H
#define _PAGE2_WEATHER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_page2_Screen2_weather
void ui_page2_Screen2_weather_screen_init(void);
extern lv_obj_t * ui_page2_Screen2_weather;
extern lv_obj_t * ui_page2_Panel_main;
extern lv_obj_t * ui_page2_Label1_date;
extern lv_obj_t * ui_page2_Label1_week;
extern lv_obj_t * ui_page2_Label1_nongli;
extern lv_obj_t * ui_page2_Label1_time;
extern lv_obj_t * ui_page2_Panel2_main_ht;
extern lv_obj_t * ui_page2_Image1_wendu;
extern lv_obj_t * ui_page2_Image2_shidu;
extern lv_obj_t * ui_page2_Label1_temp;
extern lv_obj_t * ui_page2_Label1_wendu;
extern lv_obj_t * ui_page2_Label1_shidu;
extern lv_obj_t * ui_page2_Label1_suget;
extern lv_obj_t * ui_page2_Label1_locsl;
extern lv_obj_t * ui_page2_Image4_local;
extern lv_obj_t * ui_page2_Label1_gengxing;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_images_beijing_png);    // assets/images/beijing.png
LV_IMG_DECLARE(ui_img_images_wendu_png);    // assets/images/wendu.png
LV_IMG_DECLARE(ui_img_images_shidu_png);    // assets/images/shidu.png
LV_IMG_DECLARE(ui_img_images_local_png);    // assets/images/local.png



LV_FONT_DECLARE(ui_font_Font18px);
LV_FONT_DECLARE(ui_font_Font64px);
LV_FONT_DECLARE(ui_font_Font32px);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
