// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: page2_weather

#include "../ui.h"

void ui_page2_Screen2_weather_screen_init(void)
{
    ui_page2_Screen2_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page2_Screen2_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_page2_Screen2_weather, &ui_img_images_beijing_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page2_Screen2_weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page2_Screen2_weather, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_page2_Screen2_weather, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_Screen2_weather, 105, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_page2_Panel_main = lv_obj_create(ui_page2_Screen2_weather);
    lv_obj_set_width(ui_page2_Panel_main, 639);
    lv_obj_set_height(ui_page2_Panel_main, 333);
    lv_obj_set_x(ui_page2_Panel_main, 99);
    lv_obj_set_y(ui_page2_Panel_main, 92);
    lv_obj_clear_flag(ui_page2_Panel_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_page2_Panel_main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page2_Panel_main, lv_color_hex(0x97EDA3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_Panel_main, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page2_Panel_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page2_Panel_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_date = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_date, -175);
    lv_obj_set_y(ui_page2_Label1_date, -92);
    lv_obj_set_align(ui_page2_Label1_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_date, "2024年4月21日");
    lv_obj_set_style_text_font(ui_page2_Label1_date, &ui_font_Font32px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_week = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_week, -177);
    lv_obj_set_y(ui_page2_Label1_week, -53);
    lv_obj_set_align(ui_page2_Label1_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_week, "星期日");
    lv_obj_set_style_text_font(ui_page2_Label1_week, &ui_font_Font32px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_nongli = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_nongli, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_nongli, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_nongli, -172);
    lv_obj_set_y(ui_page2_Label1_nongli, -15);
    lv_obj_set_align(ui_page2_Label1_nongli, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_nongli, "农历 三月十三 甲辰 龙年");
    lv_obj_set_style_text_font(ui_page2_Label1_nongli, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_time = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_time, -172);
    lv_obj_set_y(ui_page2_Label1_time, 54);
    lv_obj_set_align(ui_page2_Label1_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_time, "21:52");
    lv_obj_set_style_text_font(ui_page2_Label1_time, &ui_font_Font64px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Panel2_main_ht = lv_obj_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Panel2_main_ht, 215);
    lv_obj_set_height(ui_page2_Panel2_main_ht, 42);
    lv_obj_set_x(ui_page2_Panel2_main_ht, -168);
    lv_obj_set_y(ui_page2_Panel2_main_ht, 131);
    lv_obj_set_align(ui_page2_Panel2_main_ht, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page2_Panel2_main_ht, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page2_Panel2_main_ht, lv_color_hex(0xE8E2E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_Panel2_main_ht, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Image1_wendu = lv_img_create(ui_page2_Panel2_main_ht);
    lv_img_set_src(ui_page2_Image1_wendu, &ui_img_images_wendu_png);
    lv_obj_set_width(ui_page2_Image1_wendu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Image1_wendu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Image1_wendu, -58);
    lv_obj_set_y(ui_page2_Image1_wendu, 1);
    lv_obj_set_align(ui_page2_Image1_wendu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_Image1_wendu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_Image1_wendu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_Image2_shidu = lv_img_create(ui_page2_Panel2_main_ht);
    lv_img_set_src(ui_page2_Image2_shidu, &ui_img_images_shidu_png);
    lv_obj_set_width(ui_page2_Image2_shidu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Image2_shidu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Image2_shidu, 37);
    lv_obj_set_y(ui_page2_Image2_shidu, -2);
    lv_obj_set_align(ui_page2_Image2_shidu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_Image2_shidu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_Image2_shidu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_Label1_temp = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_temp, -252);
    lv_obj_set_y(ui_page2_Label1_temp, 132);
    lv_obj_set_align(ui_page2_Label1_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_temp, "室内");
    lv_obj_set_style_text_font(ui_page2_Label1_temp, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_wendu = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_wendu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_wendu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_wendu, -181);
    lv_obj_set_y(ui_page2_Label1_wendu, 132);
    lv_obj_set_align(ui_page2_Label1_wendu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_wendu, "23℃");
    lv_obj_set_style_text_font(ui_page2_Label1_wendu, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_shidu = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_shidu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_shidu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_shidu, -89);
    lv_obj_set_y(ui_page2_Label1_shidu, 130);
    lv_obj_set_align(ui_page2_Label1_shidu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_shidu, "78%");
    lv_obj_set_style_text_font(ui_page2_Label1_shidu, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_suget = lv_label_create(ui_page2_Panel_main);
    lv_obj_set_width(ui_page2_Label1_suget, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_Label1_suget, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_page2_Label1_suget, 161);
    lv_obj_set_y(ui_page2_Label1_suget, -37);
    lv_obj_set_align(ui_page2_Label1_suget, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_Label1_suget, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_Label1_suget, "下雨 雨伞 多穿衣服 ");
    lv_obj_set_style_text_color(ui_page2_Label1_suget, lv_color_hex(0xFF004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_Label1_suget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_Label1_suget, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Label1_locsl = lv_label_create(ui_page2_Screen2_weather);
    lv_obj_set_width(ui_page2_Label1_locsl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_locsl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_locsl, -301);
    lv_obj_set_y(ui_page2_Label1_locsl, -202);
    lv_obj_set_align(ui_page2_Label1_locsl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_locsl, "深圳");
    lv_obj_set_style_text_color(ui_page2_Label1_locsl, lv_color_hex(0x1BEED4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_Label1_locsl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_Label1_locsl, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_Image4_local = lv_img_create(ui_page2_Screen2_weather);
    lv_img_set_src(ui_page2_Image4_local, &ui_img_images_local_png);
    lv_obj_set_width(ui_page2_Image4_local, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_page2_Image4_local, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_page2_Image4_local, -357);
    lv_obj_set_y(ui_page2_Image4_local, -204);
    lv_obj_set_align(ui_page2_Image4_local, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_Image4_local, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_Image4_local, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_Label1_gengxing = lv_label_create(ui_page2_Screen2_weather);
    lv_obj_set_width(ui_page2_Label1_gengxing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_Label1_gengxing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_Label1_gengxing, 253);
    lv_obj_set_y(ui_page2_Label1_gengxing, -220);
    lv_obj_set_align(ui_page2_Label1_gengxing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_Label1_gengxing, "最后更新日期 4月20日 10：00");
    lv_obj_set_style_text_color(ui_page2_Label1_gengxing, lv_color_hex(0x1BEED4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_Label1_gengxing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_Label1_gengxing, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

}
