// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: page1_start

#include "../ui.h"

void ui_page1_Screen1_start_screen_init(void)
{
    ui_page1_Screen1_start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page1_Screen1_start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_page1_Screen1_start, &ui_img_images_long_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page1_Screen1_start, &ui_font_Font20px, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_page1_Screen1_start, lv_color_hex(0xE300FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page1_Screen1_start, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_page1_Label1_loadingtext = lv_label_create(ui_page1_Screen1_start);
    lv_obj_set_width(ui_page1_Label1_loadingtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page1_Label1_loadingtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page1_Label1_loadingtext, -15);
    lv_obj_set_y(ui_page1_Label1_loadingtext, 140);
    lv_obj_set_align(ui_page1_Label1_loadingtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page1_Label1_loadingtext, "正在连接WiFi");
    lv_obj_set_style_text_font(ui_page1_Label1_loadingtext, &ui_font_Font20px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pag1_Bar1_loading = lv_bar_create(ui_page1_Screen1_start);
    lv_bar_set_value(ui_pag1_Bar1_loading, 15, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_pag1_Bar1_loading, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_pag1_Bar1_loading, 695);
    lv_obj_set_height(ui_pag1_Bar1_loading, 16);
    lv_obj_set_x(ui_pag1_Bar1_loading, -10);
    lv_obj_set_y(ui_pag1_Bar1_loading, 109);
    lv_obj_set_align(ui_pag1_Bar1_loading, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_pag1_Bar1_loading, lv_color_hex(0xC700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pag1_Bar1_loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_pag1_Bar1_loading, lv_color_hex(0xFD00F7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pag1_Bar1_loading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
